# Generated by Django 3.1.6 on 2021-02-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.IntegerField(blank=True, verbose_name='Штрихкод')),
                ('desc', models.TextField(verbose_name='дополнительное описание')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('number', models.IntegerField(default=0, verbose_name='Номер товара')),
                ('amount', models.IntegerField(verbose_name='Anzahl')),
                ('image', models.ImageField(height_field=150, upload_to='', width_field=150)),
                ('add_attributes', models.ManyToManyField(to='product.Attr')),
                ('category', models.ManyToManyField(to='product.Category')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
