# Generated by Django 3.1.7 on 2021-03-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='product.Category', verbose_name='категория'),
        ),
    ]
